# Generated by Django 4.2.19 on 2025-04-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
