# Generated by Django 4.2.19 on 2025-03-24 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('ubicacion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('tarifa', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en dólares', max_digits=10)),
                ('cupon_gratis', models.BooleanField(default=False)),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, default=2.0, help_text='Tarifa base por hora en dólares', max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Superheroe',
        ),
    ]
