# Generated by Django 4.2.19 on 2025-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Superheroe',
        ),
    ]
