# Generated by Django 4.2.19 on 2025-03-01 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estacionamiento_delete_superheroe'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
