# Generated by Django 4.2.19 on 2025-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estacionamiento_fecha_alter_estacionamiento_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='cupon_gratis',
            field=models.BooleanField(default=False, verbose_name='Cupón de estacionamiento gratis'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='horas_consumidas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas consumidas'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='tarifa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarifa a pagar'),
        ),
    ]
