# Generated by Django 4.2.19 on 2025-03-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estacionamiento_cupon_gratis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='cupon_gratis',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='horas_consumidas',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='tarifa',
        ),
    ]
