# Generated by Django 4.2.19 on 2025-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_estacionamiento_cupon_gratis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='cupon_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en dólares', max_digits=10),
        ),
    ]
