# Generated by Django 4.2.19 on 2025-03-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_estacionamiento_tarifa_por_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
